FROM node:21-alpine AS development

ENV NODE_ENV development

WORKDIR /app

COPY package.json .
COPY package-lock.json .
COPY tsconfig.json .
COPY env.local .


RUN npm install

COPY . .

ADD  env.local .env 

EXPOSE 8080

ENV PORT 8080

CMD ["npm", "start"]